import Link from 'next/link'
import { PixelPanel } from '@/components/ui/PixelPanel'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-900 to-gray-800 p-8">
      <div className="max-w-4xl mx-auto">
        <Link href="/" className="text-amber-400 hover:text-amber-300 mb-8 inline-block">
          ← Back to Home
        </Link>

        <PixelPanel>
          <div className="p-8 prose prose-invert max-w-none">
            <h1 className="font-['Press_Start_2P'] text-3xl text-amber-400 mb-8">
              Terms of Service
            </h1>

            <p className="text-gray-300 mb-6">
              <strong>Last Updated: December 2024</strong>
            </p>

            <section className="mb-8">
              <h2 className="font-['Press_Start_2P'] text-xl text-amber-300 mb-4">
                Acceptance of Terms
              </h2>
              <div className="text-gray-300 space-y-4">
                <p>
                  By accessing or using DND Hero, you agree to be bound by these Terms of Service
                  and our Privacy Policy. If you do not agree, do not use our service.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="font-['Press_Start_2P'] text-xl text-amber-300 mb-4">
                Account Requirements
              </h2>
              <div className="text-gray-300 space-y-4">
                <ul className="list-disc pl-6 space-y-2">
                  <li>You must be at least 13 years old to use DND Hero</li>
                  <li>You must provide accurate account information</li>
                  <li>You are responsible for maintaining account security</li>
                  <li>One person per account; sharing accounts is prohibited</li>
                  <li>You may not create multiple accounts to bypass limitations</li>
                </ul>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="font-['Press_Start_2P'] text-xl text-amber-300 mb-4">
                Acceptable Use
              </h2>
              <div className="text-gray-300 space-y-4">
                <p>You agree NOT to:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Harass, abuse, or harm other users</li>
                  <li>Post illegal, offensive, or inappropriate content</li>
                  <li>Attempt to exploit, hack, or disrupt the service</li>
                  <li>Use the service for commercial purposes without authorization</li>
                  <li>Violate any applicable laws or regulations</li>
                  <li>Impersonate others or misrepresent your affiliation</li>
                </ul>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="font-['Press_Start_2P'] text-xl text-amber-300 mb-4">
                Content & Intellectual Property
              </h2>
              <div className="text-gray-300 space-y-4">
                <p>
                  <strong>Your Content:</strong> You retain ownership of campaign content you
                  create. By using DND Hero, you grant us a license to store, display, and process
                  your content to provide the service.
                </p>
                <p>
                  <strong>AI-Generated Content:</strong> Narratives and content generated by our AI
                  DM belong to you, but we cannot guarantee uniqueness or copyright protection.
                </p>
                <p>
                  <strong>Our Service:</strong> DND Hero's platform, design, code, and features are
                  our intellectual property. You may not copy, modify, or reverse engineer them.
                </p>
                <p>
                  <strong>D&D Content:</strong> Dungeons & Dragons, D&D, and related trademarks
                  belong to Wizards of the Coast. DND Hero is not affiliated with or endorsed by
                  Wizards of the Coast.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="font-['Press_Start_2P'] text-xl text-amber-300 mb-4">
                Subscriptions & Payments
              </h2>
              <div className="text-gray-300 space-y-4">
                <ul className="list-disc pl-6 space-y-2">
                  <li>Subscriptions renew automatically until canceled</li>
                  <li>Cancellations take effect at the end of the current billing period</li>
                  <li>No refunds for partial months unless required by law</li>
                  <li>We reserve the right to change pricing with 30 days notice</li>
                  <li>Failure to pay may result in service suspension</li>
                  <li>Credit purchases are non-refundable</li>
                </ul>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="font-['Press_Start_2P'] text-xl text-amber-300 mb-4">
                Service Availability
              </h2>
              <div className="text-gray-300 space-y-4">
                <p>
                  We strive to provide reliable service but do not guarantee 100% uptime. We may
                  perform maintenance, updates, or experience outages. We are not liable for any
                  loss resulting from service interruptions.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="font-['Press_Start_2P'] text-xl text-amber-300 mb-4">
                Termination
              </h2>
              <div className="text-gray-300 space-y-4">
                <p>We may suspend or terminate your account if you:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Violate these Terms of Service</li>
                  <li>Engage in prohibited conduct</li>
                  <li>Fail to pay subscription fees</li>
                  <li>Create risk or legal liability for us</li>
                </ul>
                <p>
                  You may delete your account at any time from your account settings. Upon
                  termination, you lose access to your campaigns and data.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="font-['Press_Start_2P'] text-xl text-amber-300 mb-4">
                Disclaimers
              </h2>
              <div className="text-gray-300 space-y-4">
                <p>
                  <strong>AS-IS SERVICE:</strong> DND Hero is provided "as is" without warranties
                  of any kind. We do not guarantee that the service will be error-free, secure, or
                  uninterrupted.
                </p>
                <p>
                  <strong>AI LIMITATIONS:</strong> Our AI DM may produce unexpected, inaccurate, or
                  inappropriate content. We are not responsible for AI-generated narratives.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="font-['Press_Start_2P'] text-xl text-amber-300 mb-4">
                Limitation of Liability
              </h2>
              <div className="text-gray-300 space-y-4">
                <p>
                  To the maximum extent permitted by law, DND Hero and its operators shall not be
                  liable for any indirect, incidental, special, or consequential damages arising
                  from your use of the service. Our total liability shall not exceed the amount you
                  paid us in the past 12 months.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="font-['Press_Start_2P'] text-xl text-amber-300 mb-4">
                Changes to Terms
              </h2>
              <div className="text-gray-300 space-y-4">
                <p>
                  We may update these Terms from time to time. Material changes will be notified
                  via email or platform notification. Continued use of DND Hero after changes
                  constitutes acceptance.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="font-['Press_Start_2P'] text-xl text-amber-300 mb-4">
                Governing Law
              </h2>
              <div className="text-gray-300 space-y-4">
                <p>
                  These Terms are governed by the laws of [Your Jurisdiction]. Any disputes shall
                  be resolved in the courts of [Your Jurisdiction].
                </p>
              </div>
            </section>

            <section>
              <h2 className="font-['Press_Start_2P'] text-xl text-amber-300 mb-4">
                Contact Us
              </h2>
              <div className="text-gray-300">
                <p>
                  Questions about these Terms? Contact us at:
                  <br />
                  <a href="mailto:legal@dndhero.com" className="text-amber-400 hover:text-amber-300">
                    legal@dndhero.com
                  </a>
                </p>
              </div>
            </section>
          </div>
        </PixelPanel>
      </div>
    </div>
  )
}
